### PR TITLE
Rename `indices` to `mask`. Closes issue #91

### PR DESCRIPTION
**Pull request by kyracho**
# Checklist
Hi, this PR changes  `_treatment_variants_indices` to `_treatment_variants_indices` in 
- `metalearner.py` 
- `xlearner.py` 
- `tlearner.py`
-  `drlearner.py`
- `test_learner.py`

Closes issue #91 

- [x] Added a `CHANGELOG.rst` entry

### CODE REVIEW

**Comment by kyracho** [comment]
Oops! Sorry, I made the mistake of forgetting to build the documentation locally, leading to several commits before it finally built successfully.

**Comment by kyracho** [comment]
Hello, I apologize for the multiple commits and any confusion this may have caused. I was working through some issues and ended up with a bit of a messy commit history. I made the mistake of forgetting to build the documentation locally, and it took several commits to rename all occurrences of the internal variable. The force-push was to amend a typo in the last commit message... embarrassing! I appreciate your understanding, and I’ll be more mindful in the future to keep things cleaner and more concise.

**Comment by kklein** [comment]
Hi Kyra - thanks a lot for your contribution - this looks great! :)

I'd have two small asks:
- Would you mind removing the changelog entry for 0.12.0? Since your change exclusively affects private, i.e. with a `_` prefix, fields, we wouldn't consider it an user-facing change. We generally only try to document user-facing changes in the changelog. Apologies that this wasn't clearer - I'll update the PR template.
- Would you mind removing the files you checked in to git in `docs/api`? These are usually auto-generated and not version-controlled by us.
Screenshot 2024-09-04 at 2 25 18 PM

**Comment by kyracho** [comment]
Hi kklein, no problem at all regarding the changes—I'll go ahead and remove the changelog entry for version 0.12.0 as well as the files checked into docs/api. Thank you for clarifying.

**Review by kklein — APPROVED** [review]
LGTM - thanks a bunch! :)

**Pull request merged**
