### PR TITLE
add support for sparse X 

### PR DESCRIPTION
**Pull request by apoorvalal**
Adds support for CSR matrix inputs for all learners [not supported elsewhere, e.g. [this](https://github.com/py-why/EconML/issues/508) open issue on econml]. Turned out to be not too bad since Kfold, integer slicing all work as usual with CSR matrices. 

I added a `safe_len` method in utils and replaced all instances of `len(X)` with `safe_len(X)` (hence the many files touched - turned out no major substantive changes were required). This also means that the `Matrix` class definition in typing now unions over array, dataframe, and csr_matrix.

Also added an [example notebook](https://github.com/apoorvalal/metalearners/blob/sparseX/docs/examples/example_sparse_inputs.ipynb) that documents massive (~8-10x) speed gains from using sparse inputs. I can't think of any obvious side-effects, but I'd defer to you folks on whether there are edge cases I haven't considered here.

# Checklist

- [x] Added a `CHANGELOG.rst` entry

### CODE REVIEW

**Comment by apoorvalal** [comment]
For completeness, I also tried the same estimation routine with [`pandas.arrays.SparseArray`](https://pandas.pydata.org/docs/reference/api/pandas.arrays.SparseArray.html) returned by [`pd.get_dummies` when `sparse=True`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html) but was unreasonably slow [I terminated the job after ~5 mins]. LGBM may not even support it, but if so the failure was silent.

**Comment by apoorvalal** [comment]
docs build was previously failing due to `mypy` getting annoyed at cell magics, is now failing due to 
image

happens only on the build system; local run of `postinstall` works fine. 

will likely need some metadata tweaking; will try to take care of this later but feel free to change things around [you have write access to my fork and can make changes directly]

**Review by kklein — APPROVED** [review]
LGTM - thanks a lot! :)

Feel free to squash and merge

**Comment by apoorvalal** [comment]
don't think i have the privileges; would be great if you could.

image

thanks again; excited to use this.

**Comment by kklein** [comment]
We might add 1-2 changes at the beginning of next week and will the probably release version 0.11.0 by end of next week. :)

**Pull request merged**
